// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: BJ25 Dash Display

#include "../ui.h"

void ui_comp_Background_create_hook(lv_obj_t * comp)
{
}
